### PR TITLE
fix: replace deprecated PushedDate by AuthoredDate, add Author to the result

### PR DESCRIPTION
**Pull request by maksimnarkevichdp**
image
image

### CODE REVIEW

**Review by alv91 — APPROVED** [review]

**Comment by maksimnarkevichdp** [comment]
@alv91 could you please create a tag for the commit merged into master? Unfortunately I don't have permissions to do that

**Comment by Yalpa** [comment]
It was removed but in `our` eyes it was `0001-01-01`  so any conditions in apps that are using actions and using `pushedDate` stopped working. Of course it was giving false positives but with removal all of the conditions were automatically false

**Comment by maksimnarkevichdp** [comment]
> It was removed but in `our` eyes it was `0001-01-01` so any conditions in apps that are using actions and using `pushedDate` stopped working. Of course it was giving false positives but with removal all of the conditions were automatically false

Hey @Yalpa, I am sorry if it brought you some problems, it was my first PR in that repo and I didn't know it could impact your team much. Thank you for understanding 🙏

**Comment by Yalpa** [comment]
@maksimnarkevichdp no hard feelings. I just posted here so this could be lesson learnt for the future :)

**Pull request merged**
